POST http://0.0.0.0:8080/api/users
Content-Type: application/json

{
  "username": "manuelernesto",
  "password": "A2j34567?0"
}

###

PUT http://0.0.0.0:8080/api/users/1/new-password
Content-Type: application/json

{
  "oldPassword": "A2j34567?0",
  "newPassword": "A2j34567?1"
}
