POST http://0.0.0.0:8080/api/users
Content-Type: application/json

{
  "username": "manuelernest01",
  "password": "A2j34567?0",
  "email": "hi@manuelernesto.dev"
}

###

PUT http://0.0.0.0:8080/api/users/1/new-password
Content-Type: application/json

{
  "oldPassword": "A2j34567?0",
  "newPassword": "A2j34567?1"
}


###
GET 0.0.0.0:8080/api/users/2233bcfe-b570-423b-b51b-17363a0be578
Content-Type: application/json

###
DELETE 0.0.0.0:8080/api/users/2233bcfe-b570-423b-b51b-17363a0be57
Content-Type: application/json