ktor:
  application:
    modules:
      - dev.manuelernesto.ApplicationKt.module
  deployment:
    port: 8080
  database:
    driver: "org.postgresql.Driver"
    url: $DB_URL
    username: $DB_USER
    password: $DB_PASSWORD