ktor:
  application:
    modules:
      - dev.manuelernesto.ApplicationKt.module
  deployment:
    port: 8080
  database:
    url:
      - "jdbc:postgresql://localhost:5432/money_tracker_db"
    driver:
      - "org.postgresql.Driver"
    user:
      - user
    password:
      - pwd